name: 'ğŸ¢ Next.js Build'

on:
  push:
    branches-ignore:
      - main  # main branch is handled by test-coverage.yml

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›¬
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Cache node_modules ğŸ§ 
        id: cache-node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}

      - name: Setup Node âš™ï¸
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Install dependencies ğŸ“©
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Lint code ğŸ’…
        run: npm run lint

      - name: Build Next.js ğŸ“¦
        run: npm run build

      - name: Cache Next.js build âš¡
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-next-${{ hashFiles('package-lock.json') }}
